// Generated by CoffeeScript 1.7.1
(function() {
  window.TextForm = (function() {
    function TextForm(options) {
      this.form = options.$form;
      this.box = options.$box;
    }

    TextForm.prototype.reflect = function() {
      return this.box.html('<div>' + this.form.val().replace(/[\n\r]/g, "<br />") + '</div>');
    };

    return TextForm;

  })();

}).call(this);
